//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoucherEntities : DbContext
    {
        public VoucherEntities()
            : base("name=VoucherEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CVoucher> CVouchers { get; set; }
        public DbSet<Voucher> Vouchers { get; set; }
        public DbSet<MAVoucher> MAVouchers { get; set; }
        public DbSet<PBVoucher> PBVouchers { get; set; }
        public DbSet<TAVoucher> TAVouchers { get; set; }
    }
}
