//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voucher
    {
        [Display(Name = "Voucher Id")]
        public int VoucherID { get; set; }
        [Display(Name = "Submitted By")]
        public string SubmittedBy { get; set; }
        [Display(Name = "Voucher Type")]
        public string VoucherType { get; set; }
        [Display(Name = "Submit Date")]
        public Nullable<System.DateTime> SubmitDate { get; set; }
        [Display(Name = "Status(DM)")]
        public string StatusByDM { get; set; }
        [Display(Name = "Status(FSO)")]
        public string StatusByFSO { get; set; }
        [Display(Name = "Employee Id")]
        public Nullable<int> EmployeeID { get; set; }
    }
}
